[package]
name = "blockcraft-host"
version = "0.2.0"
description = "Blockcraft Server - host a game from your own machine"
authors = ["Blockcraft"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "blockcraft_host_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
